// <auto-generated />
namespace Young.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class removeTermPE : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeTermPE));
        
        string IMigrationMetadata.Id
        {
            get { return "201401140904417_removeTermPE"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
